stages:
    - init
    - build

before_script:
    - export GOROOT="/opt/go"
    - export GOPATH="/home/gitlab-runner/go"
    - export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
    - gmake dep

copy_dir:
    stage: init
    script:
    - gmake copy_dir

build:
  stage: build
  script:
    - gmake
    - echo "Finished"


