stages:
        - init
        - build
        - trigger-middlewares

before_script:
        - export GOROOT="/usr/local/go"
        - export GOPATH="/home/gitlab-runner/go"
        - export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
        - export HCCPATH="$GOPATH/src/hcc"
        - export TOKNOVNC="5923fd713d02257b3106a7a0edf6d3"
        - export TOKCLARINET="2e3188778e405f731bc2f52776d65c"
        - export TOKPIANO="0edd217133f45d8bf561f4fb9ac8ea"

copy_dir:
        stage: init
        script:
                - make copy_dir
        only:
                - master

build:
        stage: build
        script:
                - make
                - echo "Finished"
        only:
                - master

trigger_violin_novnc:
    stage: trigger-middlewares
    script:
        - "curl -X POST -F token=$TOKNOVNC -F ref=master http://210.207.104.150:8100/api/v4/projects/63/trigger/pipeline"
        - "curl -X POST -F token=$TOKCLARINET -F ref=master http://210.207.104.150:8100/api/v4/projects/63/trigger/pipeline"
        - "curl -X POST -F token=$TOKPIANO -F ref=master http://210.207.104.150:8100/api/v4/projects/63/trigger/pipeline"
    only:
        - master