stages:
        - init
        - build

before_script:
        - export GOROOT="/opt/go"
        - export GOPATH="/home/gitlab-runner/go"
        - export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"

copy_dir:
        stage: init
        script:
                - make copy_dir
        only:
                - master

build:
        stage: build
        script:
                - make
                - echo "Finished"
        only:
                - master

